@startuml
'https://plantuml.com/sequence-diagram

title Domain Model / As User, I want to log in an account

skinparam classAttributeIconSize 0
hide circle
hide methods

class User{
    -username
    -password
    -photo
}

class Role{
    -type
}

Role "1" <.right. "1" User: Has

@enduml
