@startuml

skinparam classAttributeIconSize 0
hide circle
hide methods

class User{
    -username
    -password
    -photo
}

class Subscriptions {
    -startDate
    -endDate
    -paymentType
    -activeStatus
    -planName
    -userName
}


class Role{
    -type
}


Role "1" <.right. "1" User: has
User "1" .right.> "1" Subscriptions: has

@enduml
