@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title Sequence Diagram/ As Marketing director, I want to update a plan

autonumber

actor "Marketing Director" as Ac
participant ":PlanController" as Ctrl
participant ":PlansService" as Serv
participant ":PlansRepository" as Repo
participant ":CreatePlanJsonProducer" as producer
participant ":Plans" as Mapper

Ac -> Ctrl : PATCH/plans/update/{name}
Ctrl -> Serv :Plans plans = partialUpdate(name, editPlanRequest)
Serv -> Repo :Optional<Plans> plans = findByName_Name(resource.getName())
Repo --> Serv : plans
note left
1) Service will check if plan exists

If 1 comes true,
Service will trow IllegalArgumentException
end note
Serv -> Mapper :plan.update(editPlanRequest)
Mapper --> Serv: plan
deactivate producer
Serv -> Repo: save(obj)
Repo --> Serv: plan
Serv -> producer : sendMessage(obj)
Serv --> Ctrl: plan
Ac <-- Ctrl : plan

@enduml
