@startuml
'https://plantuml.com/sequence-diagram

title Domain Model / As Marketing director, I want to define a new Plan

skinparam classAttributeIconSize 0
hide circle
hide methods

class User{
    -username
    -password
    -photo
}

class Plans{
    -name,
       - description
        - numberOfMinutes
        -maximumNumberOfUsers
        -musicCollection
         -musicSuggestion
         -annualFee
         -monthlyFee
         -active
         -promoted
}

class Role{
    -type
}


Role "1" <.right. "1" User: Has
User "1" .right.> "1" Plans: Creates

@enduml
