@startuml
'autocomplete on
autonumber

title Software Design Document - Deactivate a Plan

actor "Marketing Director" as Ac
participant "planC[n]:planC" as PC
participant "PlanQ[n]:planQ" as PQ
participant "SubsC[n]:SubsC" as SC
participant "SubsQ[n]:SubsQ:" as SQ
participant "Message Broker:" as mb

Ac -> PC ++ : PATCH /plans/deactivate/{name}
PC -> PC : save(plan)
PC -> mb ++ : publish(deactivated_plan, plan)
note left
[n] represents the instances
it can be n instances
end note
PC --> Ac -- : informs operation (in)success

mb -> PC ++ : notify(deactivated_plan, plan)
PC -> PC -- : save(plan)

mb -> PQ ++ : notify(deactivated_plan, plan)
PQ -> PQ -- : save(plan)

mb -> SC ++ : notify(deactivated_plan, plan)
SC -> SC -- : save(plan)

mb -> SQ ++ : notify(deactivated_plan, plan)
SQ -> SQ : save(plan)

deactivate mb

@enduml
