@startuml
'autocomplete on
autonumber

title Software Design Document - As User, I want to login an account

participant "userQ[n]:UserQ" as UQ
participant "Message Broker:" as mb

activate mb
UQ -> mb : subscribe(register_user)
deactivate mb

note left
[n] represents the the instances
it can be n instances
end note

@enduml
